# Generated by Django 5.2 on 2025-07-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewpost", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewmodel",
            name="project_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
