# Generated by Django 5.2 on 2025-07-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="favorite_count",
            field=models.IntegerField(default=0),
        ),
    ]
