# Generated by Django 5.2 on 2025-07-30 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("PUBLIC", "公開"), ("PRIVATE", "非公開")],
                default="PUBLIC",
                max_length=10,
            ),
        ),
    ]
