# Generated by Django 5.2 on 2025-07-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="avator",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
