# Generated by Django 5.2 on 2025-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_avator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="avator",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
