# Generated by Django 5.2 on 2025-07-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="follower_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="following_count",
            field=models.IntegerField(default=0),
        ),
    ]
