# Generated by Django 5.2 on 2025-07-30 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_account_follower_count_account_following_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="follower_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follow_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follow_owner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
